
version: '1'
services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'  # Map host port 3000 to container port 3000
    volumes:
      - .:/usr/src/app  # Map the current directory on the host to /usr/src/app in the container

  auth: 
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app  
  paments: 
    build: 
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app     
  mongo:
    image: mongo

